name: dcore
description: Core Flutter project for DCore

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# version: 1.0.1+1 # ios
version: 1.0.1+1 # android

environment:
  sdk: ">=3.6.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # App UI
  # flutter_datetime_picker: ^1.5.1
  # cupertino_icons: ^1.0.8
  # carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0 # App icons
  cached_network_image: ^3.4.1
  flutter_widget_from_html_core: ^0.16.0
  html: ^0.15.6
  flutter_easyloading: ^3.0.5
  video_player: ^2.9.5
  just_audio: ^0.10.2
  camera: ^0.11.1
  lottie: ^3.3.1
  syncfusion_flutter_datepicker: ^29.1.41
  flutter_polyline_points: ^2.1.0
  flutter_screenutil: ^5.9.3
  agora_rtc_engine: ^6.5.1
  pin_code_fields: ^8.0.1
  flutter_animate: ^4.5.2
  qr_flutter: ^4.1.0
  gal: ^2.3.1
  screenshot: ^3.0.0
  webview_flutter: ^4.11.0
  photo_view: ^0.15.0
  flutter_slidable: ^4.0.0


  # audioplayers: ^6.1.0
  # animations: ^2.0.11
  # youtube_player_flutter: ^9.0.1
  # flutter_onboarding_slider: ^1.0.8 # App introduce plash screen
  # expandable_text: ^2.3.0
  # just_audio: ^0.9.30
  # pin_code_fields: ^7.4.0

  # App formatting
  intl: ^0.19.0
  darq: ^2.0.0
  uuid: ^4.5.1
  fpdart: ^1.1.1
  # rxdart: ^0.28.0

  # App networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2

  # App Localizations
  flutter_localizations:
    sdk: flutter

  # App State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  # equatable: ^2.0.7

  # App Services 
  # App Storage Services
  hydrated_bloc: ^10.0.0
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5

  # App Permissions Services
  permission_handler: ^12.0.0+1

  # App Navigation Services
  url_launcher: ^6.3.1
  go_router: ^15.1.2

  # App Dependencies Injection Services
  get_it: ^8.0.3
  injectable: ^2.5.0

  # App Logger
  logger: ^2.5.0

  # App Purchases Services
  in_app_purchase: ^3.2.1
  # purchases_flutter: ^8.2.2

  # App Ads Services
  # google_mobile_ads: ^3.0.0
  # unity_ads_plugin: ^0.3.7

  # App Map Services
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # App Firebase Services
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3

  # App Notification Services
  firebase_messaging: ^15.2.5
  awesome_notifications: ^0.10.1

  # App Models and Utils
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

  # App File Services
  file_picker: ^10.1.5
  image_picker: ^1.1.2
  device_info_plus: ^11.4.0
  cloud_firestore: ^5.6.7
  collection: ^1.19.1
  get_thumbnail_video: ^0.7.3

  # App Share Services
  share_plus: ^11.0.0

  # App Video Services
  video_compress: ^3.1.4

  # App Scanner Services
  mobile_scanner: ^7.0.0

  # App Open Settings Services
  open_settings_plus: ^0.4.0

  # App Tracking Services
  sentry_flutter: ^8.14.2
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5

  # ffmpeg_kit_flutter_new: ^1.1.0

  # App Socket Services
  socket_io_client: ^3.1.2

  # App Deep Links Services
  app_links: ^6.4.0

  # App Wakelock Services
  wakelock_plus: ^1.3.2

  # App Isolate Services
  flutter_isolate: ^2.1.0

  # App External Services
  # timezone: ^0.9.2
  # crypto: ^3.0.2

dependency_overrides:
  awesome_notifications:
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      # This tells pub to use the current HEAD of the PR (the pull request's fix):
      ref: refs/pull/990/head
  # ffmpeg_kit_flutter_new:
  #   git:
  #     url: https://github.com/tanersener/ffmpeg-kit.git
  #     path: flutter/flutter
  #     ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  meta: ^1.16.0

  # App Generators
  # To generate code run this command
  # flutter pub run build_runner build --delete-conflicting-outputs
  # or this command
  # dart run build_runner build --delete-conflicting-outputs
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  go_router_builder: ^2.9.0
  freezed: ^3.0.6
  flutter_gen: ^5.10.0

  # App Change Info

  # To change app info run this command
  # flutter pub run flutter_launcher_icons
  # or this command
  # dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.14.3
  
  # To change app package name run this command
  # flutter pub run change_app_package_name:main com.new.package.name
  # or this command
  # dart run change_app_package_name:main com.new.package.name
  change_app_package_name: ^1.5.0
  flutter_flavorizr: ^2.4.0


  # Active rename tool, run this command
  # flutter pub global activate rename
  # To change app name run this command
  # rename setAppName -t ios,android,macos,linux,web,windows -v "YourAppName"

  # To change app bundle id run this command
  # rename setBundleId -t ios,android,macos,linux,web,windows -v "com.your.app.id"

# Flutter gen environment setup
flutter_gen:
  # Optional
  output: lib/core/constants/gen/
  # Optional
  line_length: 200
  # Optional
  parse_metadata: false

  # Optional
  integrations:
    image: true
    flutter_svg: false
    rive: false
    lottie: false

  assets:
    # Optional
    enabled: true
    # Optional
    outputs:
      # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false
      # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: dot-delimiter
      class_name: AppAsset
    exclude: []

  fonts:
    # Optional
    enabled: true
    # Optional
    outputs:
      class_name: AppFont

  colors:
    # Optional
    enabled: true
    # Optional
    inputs: []
    # Optional
    outputs:
      class_name: ColorName

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/fonts/
    - assets/gif/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/texts/
    # - assets/video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: BeVNPro
      fonts:
        - asset: assets/fonts/BeVNPro/BeVietnamPro-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/Gilroy/Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/Gilroy/Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy/Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Gilroy/Gilroy-Bold.otf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter_intl:
#   enabled: true # Required. Must be set to true to activate the package. Default: false
#   class_name: S # Optional. Sets the name for the generated localization class. Default: S
#   main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#   arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
#   output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
#   use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
#   localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
#     project_id: # Get it from the https://app.localizely.com/projects page.
#     branch: # Get it from the "Branches" page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
#     upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
#     upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
#     upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
#     upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
#     upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
#     download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
#     download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
#     download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
#     ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false


