part of 'themes.dart';

mixin AppThemeUtil {
  static final lightTheme = ThemeData(
    useMaterial3: true,
    fontFamily: AppFont.lexend,
    cardColor: const Color(0xFFFFFFFF),
    canvasColor: const Color(0xFFFFFFFF),
    primarySwatch: Colors.blue,
    menuTheme: LightTheme.menuTheme(),
    colorScheme: LightTheme.colorScheme(),
    scaffoldBackgroundColor: const Color(0xFFFFFFFF),
    appBarTheme: LightTheme.appBarTheme(),
    bottomNavigationBarTheme: LightTheme.bottomNavBarTheme(),
    inputDecorationTheme: LightTheme.inputDecorationTheme(),
    textTheme: LightTheme.textTheme(),
    tabBarTheme: LightTheme.tabBarTheme(),
    textButtonTheme: LightTheme.textButtonTheme(),
    elevatedButtonTheme: LightTheme.elevatedButtonTheme(),
    filledButtonTheme: LightTheme.filledButtonTheme(),
    outlinedButtonTheme: LightTheme.outlinedButtonTheme(),
    segmentedButtonTheme: LightTheme.segmentedButtonTheme(),
    actionIconTheme: LightTheme.actionIconTheme(),
    bannerTheme: LightTheme.bannerTheme(),
    switchTheme: LightTheme.switchTheme(),
    bottomSheetTheme: LightTheme.bottomSheetTheme(),
    timePickerTheme: LightTheme.timePickerTheme(),
    buttonTheme: LightTheme.buttonTheme(),
    iconButtonTheme: LightTheme.iconButtonTheme(),
    floatingActionButtonTheme: LightTheme.floatingActionButtonTheme(),
    expansionTileTheme: LightTheme.expansionTileTheme(),
    menuButtonTheme: LightTheme.menuButtonTheme(),
    popupMenuTheme: LightTheme.popupMenuTheme(),
    dataTableTheme: LightTheme.dataTableTheme(),
    menuBarTheme: LightTheme.menuBarTheme(),
    navigationBarTheme: LightTheme.navigationBarTheme(),
    progressIndicatorTheme: LightTheme.progressIndicatorTheme(),
    navigationDrawerTheme: LightTheme.navigationDrawerTheme(),
    navigationRailTheme: LightTheme.navigationRailTheme(),
    chipTheme: LightTheme.chipTheme(),
    radioTheme: LightTheme.radioButtonTheme(),
    iconTheme: LightTheme.iconTheme(),
    checkboxTheme: LightTheme.checkBoxTheme(),
    listTileTheme: LightTheme.listTitleTheme(),
    cardTheme: LightTheme.cardTheme(),
    snackBarTheme: LightTheme.snackBarTheme(),
    drawerTheme: LightTheme.drawerTheme(),
    dividerTheme: LightTheme.dividerTheme(),
    dialogTheme: LightTheme.dialogTheme(),
    dropdownMenuTheme: LightTheme.dropdownMenuTheme(),
    badgeTheme: LightTheme.badgeTheme(),
    bottomAppBarTheme: LightTheme.bottomAppBarTheme(),
    toggleButtonsTheme: LightTheme.toggleButtonTheme(),
    datePickerTheme: LightTheme.datePickerTheme(),
    visualDensity: VisualDensity.standard,
    unselectedWidgetColor: const Color(0X8A000000),
    dividerColor: const Color(0XFFE9E9E9),
    pageTransitionsTheme: LightTheme.pageTransitionTheme(),
  );

  static final darkTheme = ThemeData(
    useMaterial3: true,
    fontFamily: AppFont.lexend,
    colorScheme: DarkTheme.colorScheme(),
    cardColor: const Color(0xFF000000),
    canvasColor: Colors.transparent,
    menuTheme: DarkTheme.menuTheme(),
    scaffoldBackgroundColor: const Color(0xFF000000),
    appBarTheme: DarkTheme.appBarTheme(),
    bottomNavigationBarTheme: DarkTheme.bottomNavBarTheme(),
    inputDecorationTheme: DarkTheme.inputDecorationTheme(),
    textTheme: DarkTheme.textTheme(),
    tabBarTheme: DarkTheme.tabBarTheme(),
    textButtonTheme: DarkTheme.textButtonTheme(),
    elevatedButtonTheme: DarkTheme.elevatedButtonTheme(),
    filledButtonTheme: DarkTheme.filledButtonTheme(),
    outlinedButtonTheme: DarkTheme.outlinedButtonTheme(),
    segmentedButtonTheme: DarkTheme.segmentedButtonTheme(),
    actionIconTheme: DarkTheme.actionIconTheme(),
    bannerTheme: DarkTheme.bannerTheme(),
    bottomSheetTheme: DarkTheme.bottomSheetTheme(),
    timePickerTheme: DarkTheme.timePickerTheme(),
    buttonTheme: DarkTheme.buttonTheme(),
    iconButtonTheme: DarkTheme.iconButtonTheme(),
    floatingActionButtonTheme: DarkTheme.floatingActionButtonTheme(),
    expansionTileTheme: DarkTheme.expansionTileTheme(),
    menuButtonTheme: DarkTheme.menuButtonTheme(),
    popupMenuTheme: DarkTheme.popupMenuTheme(),
    dataTableTheme: DarkTheme.dataTableTheme(),
    menuBarTheme: DarkTheme.menuBarTheme(),
    navigationBarTheme: DarkTheme.navigationBarTheme(),
    progressIndicatorTheme: DarkTheme.progressIndicatorTheme(),
    navigationDrawerTheme: DarkTheme.navigationDrawerTheme(),
    navigationRailTheme: DarkTheme.navigationRailTheme(),
    chipTheme: DarkTheme.chipTheme(),
    switchTheme: DarkTheme.switchTheme(),
    radioTheme: DarkTheme.radioButtonTheme(),
    iconTheme: DarkTheme.iconTheme(),
    checkboxTheme: DarkTheme.checkBoxTheme(),
    listTileTheme: DarkTheme.listTitleTheme(),
    cardTheme: DarkTheme.cardTheme(),
    snackBarTheme: DarkTheme.snackBarTheme(),
    drawerTheme: DarkTheme.drawerTheme(),
    dividerTheme: DarkTheme.dividerTheme(),
    dialogTheme: DarkTheme.dialogTheme(),
    dropdownMenuTheme: DarkTheme.dropdownMenuTheme(),
    badgeTheme: DarkTheme.badgeTheme(),
    bottomAppBarTheme: DarkTheme.bottomAppBarTheme(),
    toggleButtonsTheme: DarkTheme.toggleButtonTheme(),
    datePickerTheme: DarkTheme.datePickerTheme(),
    visualDensity: VisualDensity.standard,
    unselectedWidgetColor: const Color(0X8A000000),
    dividerColor: const Color(0XFFE9E9E9),
    pageTransitionsTheme: DarkTheme.pageTransitionTheme(),
  );
}
